include("ProximalActionTest.jl")
include("ProximalPMTest.jl")
include("ProximalAvgTest.jl")
include("ContinuityEnforcerTest.jl")
include("KProjectionTest.jl")
include("ProximalEQTest.jl")

println("Testing Projection to B")
test_proj_B(1)
println("Testing Proximal Mapping of IJpm_star")
test_prox_IJpm_star()
println("Testing Proximal Mapping of IJavg_star")
test_prox_IJavg_star()
println("Testing CE Enforcement")
test_ce_target_formation()
test_ce_system_formation()
test_ce_enforcer()
println("Testing Projection to KTop")
test_proj_ktop()
println("Testing Projection to Jeq")
test_proj_IJeq()
